import fs from 'fs';
import path from 'path';

const distDir = path.resolve('dist');
const indexPath = path.join(distDir, 'index.html');
const phpPath = path.join(distDir, 'index.php');

if (!fs.existsSync(indexPath)) {
    console.error('dist/index.html not found. Run npm run build first.');
    process.exit(1);
}

// Read the generated index.html
let html = fs.readFileSync(indexPath, 'utf8');

// PHP Logic to be prepended
const phpLogic = `<?php
/**
 * Dynamic SEO Handler
 * Generated by post-build.js
 */

// 1. Robust HTTPS & Domain Detection
$protocol = "http";
if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') {
    $protocol = "https";
} elseif (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
    $protocol = "https";
}

$host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'amulpackaging.in';
$site_url = $protocol . "://" . $host;
$request_uri = $_SERVER['REQUEST_URI'];
$full_url = $site_url . $request_uri;

// 2. Load Data Safely
$page_seo = null;
$schema = '';

// Load helper functions and data
if (file_exists('seo_data.php')) {
    include_once 'seo_data.php';
}
if (file_exists('product_data.php')) {
    include_once 'product_data.php';
}

// Helper to get SEO config if function exists
function safeGetSEO($page, $url) {
    if (function_exists('getSEOConfig')) {
        return getSEOConfig($page, $url);
    }
    return [
        'title' => 'Amul Packaging | Flexible Packaging Solutions',
        'description' => 'Leading provider of flexible packaging solutions.',
        'keywords' => 'packaging, amul packaging',
        'image' => '/img/logo.png',
        'url' => $url
    ];
}

// 3. Route Matching Logic
$path = parse_url($request_uri, PHP_URL_PATH);
$path = rtrim($path, '/');
if (empty($path)) $path = '';

// Default SEO
$page_seo = safeGetSEO('home', $site_url);

if ($path === '' || $path === '/') {
    $page_seo = safeGetSEO('home', $site_url);
} elseif ($path === '/about') {
    $page_seo = safeGetSEO('about', $site_url);
} elseif ($path === '/products') {
    $page_seo = safeGetSEO('products', $site_url);
} elseif ($path === '/services') {
    $page_seo = safeGetSEO('services', $site_url);
} elseif ($path === '/contact') {
    $page_seo = safeGetSEO('contact', $site_url);
} elseif ($path === '/industriesweserve') {
    $page_seo = safeGetSEO('industries', $site_url);
} elseif ($path === '/privacyPolicy') {
    $page_seo = safeGetSEO('privacy', $site_url);
} elseif ($path === '/termCondition') {
    $page_seo = safeGetSEO('terms', $site_url);
} elseif ($path === '/services/stand-up-pouch-manufacturer-in-bhiwandi') {
    $page_seo = safeGetSEO('service_standup', $site_url);
} elseif ($path === '/services/flat-bottom-pouch-supplier-in-bhiwandi') {
    $page_seo = safeGetSEO('service_flatbottom', $site_url);
} elseif ($path === '/services/spout-pouch-in-mumbai') {
    $page_seo = safeGetSEO('service_spout', $site_url);
} elseif ($path === '/services/vacuum-pouch-In-bhiwandi') {
    $page_seo = safeGetSEO('service_vacuum', $site_url);
} elseif ($path === '/services/laminated-roll-stock-in-mumbai') {
    $page_seo = safeGetSEO('service_rollstock', $site_url);
} elseif ($path === '/services/poly-bags-manufacturer-in-mumbai') {
    $page_seo = safeGetSEO('service_polybags', $site_url);
} elseif ($path === '/services/pillow-pouch') {
    $page_seo = safeGetSEO('service_pillow', $site_url);
} elseif (preg_match('/^\\/products\\/(\\d+)\\/?([a-zA-Z0-9-]+)?$/', $path, $matches)) {
    // Product Detail Page
    $product_id = intval($matches[1]);
    $product = null;
    if (isset($products) && is_array($products)) {
        foreach ($products as $p) {
            if ($p['id'] === $product_id) {
                $product = $p;
                break;
            }
        }
    }
    
    if ($product) {
        $page_seo = [
            'title' => $product['seoTitle'],
            'description' => $product['seoDescription'],
            'keywords' => isset($product['seoKeywords']) ? $product['seoKeywords'] : $product['name'] . ", flexible packaging",
            'image' => $site_url . $product['image'],
            'url' => $site_url . $path
        ];
        
        $schema = '<script type="application/ld+json">
        {
          "@context": "https://schema.org",
          "@type": "Product",
          "name": "' . addslashes($product['name']) . '",
          "description": "' . addslashes($product['seoDescription']) . '",
          "image": "' . $site_url . $product['image'] . '",
          "brand": { "@type": "Brand", "name": "Amul Packaging" },
          "offers": {
            "@type": "Offer",
            "availability": "https://schema.org/InStock",
            "seller": { "@type": "Organization", "name": "Amul Packaging" }
          }
        }
        </script>';
    }
} elseif ($path === '/blog') {
    $page_seo = safeGetSEO('home', $site_url); // Or a specific blog list SEO
    $page_seo['title'] = "Packaging Blog | Industry Insights | Amul Packaging";
} elseif (preg_match('/^\\/blog\\/(\\d+)\\/?([a-zA-Z0-9-]+)?$/', $path, $matches) || preg_match('/^\\/blog\\/([a-zA-Z0-9-]+)$/', $path, $matches)) {
    // Blog Detail Page - Singular /blog/ to match React routes
    try {
        if (file_exists('api/db_connection.php')) {
            include_once 'api/db_connection.php';
            if (class_exists('DatabasePDO')) {
                $db = new DatabasePDO();
                $conn = $db->getConnection();
                
                $identifier = $matches[1];
                if (is_numeric($identifier)) {
                    $stmt = $conn->prepare("SELECT * FROM blogs WHERE id = ? AND status = 1 LIMIT 1");
                    $stmt->execute([$identifier]);
                } else {
                    $stmt = $conn->prepare("SELECT * FROM blogs WHERE slug = ? AND status = 1 LIMIT 1");
                    $stmt->execute([$identifier]);
                }
                
                $blog = $stmt->fetch();
                if ($blog) {
                    $page_seo = [
                        'title' => $blog['title'] . " | Blog | Amul Packaging",
                        'description' => $blog['excerpt'] ?: substr(strip_tags($blog['content']), 0, 160),
                        'keywords' => "packaging blog, amul packaging, " . $blog['title'],
                        'image' => $blog['featured_image'] ? ($site_url . $blog['featured_image']) : ($site_url . "/img/logo.png"),
                        'url' => $site_url . $path
                    ];
                    
                    $schema = '<script type="application/ld+json">
                    {
                      "@context": "https://schema.org",
                      "@type": "BlogPosting",
                      "headline": "' . addslashes($blog['title']) . '",
                      "image": "' . ($blog['featured_image'] ? ($site_url . $blog['featured_image']) : ($site_url . "/img/logo.png")) . '",
                      "author": { "@type": "Person", "name": "' . addslashes($blog['author'] ?: 'Amul Packaging') . '" },
                      "datePublished": "' . $blog['published_at'] . '",
                      "description": "' . addslashes($blog['excerpt'] ?: substr(strip_tags($blog['content']), 0, 160)) . '"
                    }
                    </script>';
                }
            }
        }
    } catch (Exception $e) {
        // Silently fail and use default SEO
    }
}

// 4. Final Data Preparation
$title = htmlspecialchars($page_seo['title']);
$description = htmlspecialchars($page_seo['description']);
$keywords = htmlspecialchars($page_seo['keywords']);
$image = htmlspecialchars($page_seo['image']);
$canonical = htmlspecialchars($full_url);
?>`;

// Replace the static tags in the HTML with PHP echoes
html = html.replace(/<title>.*?<\/title>/, '<title><?php echo $title; ?></title>');
html = html.replace(/<meta name="title" content=".*?" \/>/g, '<meta name="title" content="<?php echo $title; ?>" />');
html = html.replace(/<meta name="description" content=".*?" \/>/g, '<meta name="description" content="<?php echo $description; ?>" />');
html = html.replace(/<meta name="keywords" content=".*?" \/>/g, '<meta name="keywords" content="<?php echo $keywords; ?>" />');
html = html.replace(/<link rel="canonical" href=".*?" \/>/g, '<link rel="canonical" href="<?php echo $canonical; ?>" />');

// OG Tags
html = html.replace(/<meta property="og:title" content=".*?" \/>/g, '<meta property="og:title" content="<?php echo $title; ?>" />');
html = html.replace(/<meta property="og:description" content=".*?" \/>/g, '<meta property="og:description" content="<?php echo $description; ?>" />');
html = html.replace(/<meta property="og:image" content=".*?" \/>/g, '<meta property="og:image" content="<?php echo $image; ?>" />');
html = html.replace(/<meta property="og:url" content=".*?" \/>/g, '<meta property="og:url" content="<?php echo $canonical; ?>" />');

// Twitter Tags
html = html.replace(/<meta name="twitter:title" content=".*?" \/>/g, '<meta name="twitter:title" content="<?php echo $title; ?>" />');
html = html.replace(/<meta name="twitter:description" content=".*?" \/>/g, '<meta name="twitter:description" content="<?php echo $description; ?>" />');
html = html.replace(/<meta name="twitter:image" content=".*?" \/>/g, '<meta name="twitter:image" content="<?php echo $image; ?>" />');

// Schema Replacement (Replace the first organization schema)
const schemaRegex = /<script type="application\/ld\+json">[\s\S]*?<\/script>/;
const schemaReplacement = `<?php if ($schema): ?>
    <?php echo $schema; ?>
<?php else: ?>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Amul Packaging",
  "url": "https://www.amulpackaging.in",
  "logo": "https://www.amulpackaging.in/img/logo.png",
  "description": "Leading flexible packaging solutions provider with 30+ years of expertise",
  "address": {
    "@type": "PostalAddress",
    "streetAddress": "2, Pramod Prasad Building, Plot No.232. Next to Brij Albela",
    "addressLocality": "Wadala (W)",
    "addressRegion": "Mumbai",
    "postalCode": "400 031",
    "addressCountry": "IN"
  },
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+91-9004382696",
    "contactType": "sales",
    "email": "Sales@amulpackaging.in"
  },
  "foundingDate": "1990",
  "industry": "Packaging and Printing"
}
</script>
<?php endif; ?>`;

html = html.replace(schemaRegex, schemaReplacement);

// Write the new index.php
fs.writeFileSync(phpPath, phpLogic + '\n' + html);
console.log('Successfully created dist/index.php with robust SEO logic');
