const products = [
  {
    id: 1,
    name: "Standup Zipper Pouch",
    img: "/img/products/Standup-zipper-pouch.jpg",
    hoverImg: "/img/products/Standup-zipper-pouch-Main.jpg",
    bg: "bg-green-600",
    popularity: 81,
    Details:
      "Standup zipper pouches are a modern, flexible packaging solution designed to keep products fresh, secure, and visually appealing. With a stable base, they stand upright on shelves, ensuring better visibility and brand presence.",
    Features: [
      "Resealable zipper for multiple uses",
      "Strong laminated material for durability",
      "Excellent barrier against moisture, air, and aroma",
      "Lightweight, easy to store & transport",
      "Available in matte, glossy, or transparent finishes",
      "Fully customizable in size, print & design",
    ],
    Applications: [
      "Dry fruits, nuts, and snacks",
      "Spices, pulses & cereals",
      "Tea, coffee & powdered products",
      "Confectionery & bakery items",
      "Confectionery & bakery items",
      "Pet food & nutritional products",
    ],
  },

  {
    id: 2,
    name: "3 side seal  pouch",
    img: "/img/products/3-Side-Seal-Pouch.jpg",
    hoverImg: "/img/products/3-Side-Seal-Pouch-Main.jpg",
    bg: "bg-pink-600",
    popularity: 92,
    Details:
      "Three side seal pouches are simple, secure, and highly versatile packaging solutions. Sealed on three sides with one open end for filling, they are ideal for single-use or portion-sized products, ensuring freshness and product protection.",
    Features: [
      "Strong seals on three sides for durability & safety",
      "Excellent barrier against moisture, air & aroma",
      "Cost-effective & easy to produce in bulk",
      "Compact design, convenient for storage & transport",
      "Compact design, convenient for storage & transport",
      "Customizable sizes, shapes & high-quality printing",
    ],
    Applications: [
      "Single-serve snacks & confectionery",
      "Spices, condiments & powdered mixes",
      "Pharmaceuticals & medical products",
      "Samples, trial packs & promotional items",
      "Frozen foods, sauces & liquid packaging",
      "Nutraceuticals & pet treats",
    ],
  },

  {
    id: 3,
    name: "Flat Bottom Pouch",
    img: "/img/products/Flat-Bottom-Pouch.jpg",
    hoverImg: "/img/products/Flat-Bottom-Pouch-Main.jpg",
    bg: "bg-yellow-400",
    popularity: 88,
    Details:
      "Flat bottom pouches are premium packaging solutions designed for maximum stability, storage efficiency, and shelf appeal. With a strong base and five printable panels, they offer excellent branding space while maintaining product freshness and durability.",
    Features: [
      "Sturdy flat base for upright display & better shelf presence",
      "High barrier protection against moisture, air & aroma",
      "Space-efficient design for stacking & storage",
      "Available in matte, glossy, kraft & transparent finishes",
      "Multiple closure options – zipper, tin-tie, or valve",
      "Customizable sizes, shapes & printing for brand identity",
    ],
    Applications: [
      "Coffee & tea packaging",
      "Dry fruits, nuts & snacks",
      "Spices, cereals & grains",
      "Protein powders & nutritional supplements",
      "Pet food & treats",
      "Confectionery, bakery & premium food products",
    ],
  },
  {
    id: 4,
    name: "Centre Seal Pouch",
    img: "/img/products/Centre Seal Pouch.jpg",
    hoverImg: "/img/products/Centre-Seal-Pouch-Main.jpg",
    bg: "bg-blue-600",
    popularity: 76,
    Details:
      "Center seal pouches are one of the most common and cost-effective packaging formats, designed with a seal running down the back of the pouch. They provide excellent protection, extended shelf life, and are ideal for high-volume packaging needs.",
    Features: [
      "Strong back seal for secure & durable packaging",
      "Strong back seal for secure & durable packaging",
      "Economical & efficient for bulk production",
      "Lightweight, easy to transport & store",
      "Available in glossy, matte, metallic & transparent finishes",
      "Customizable sizes, designs & printing options",
    ],
    Applications: [
      "Snacks, chips & confectionery",
      "Biscuits & bakery items",
      "Spices, pulses & powdered products",
      "Frozen & processed foods",
      "Pharmaceuticals & nutraceuticals",
      "Pet food & fertilizers",
    ],
  },
  {
    id: 5,
    name: "Quad Seal Pouch",
    img: "/img/products/Quad-Seal-Pouch.jpg",
    hoverImg: "/img/products/Quad-Seal-Pouch-Main.jpg",
    bg: "bg-red-500",
    popularity: 64,
    Details:
      "Quad seal pouches are premium packaging formats designed with four vertical seals, giving them superior strength and a box-like structure. This design allows them to hold heavier products, stand firm on shelves, and maximize branding with multiple printable panels.",
    Features: [
      "Four reinforced seals for extra strength & durability",
      "Box-shaped structure for better shelf stability",
      "Ample branding space on front, back & side panels",
      "High barrier protection against moisture, aroma & air",
      "Available in matte, glossy, kraft & metallic finishes",
      "Customizable with zipper, valve & various sizes",
    ],
    Applications: [
      "Coffee & tea packaging",
      "Protein powders & nutritional products",
      "Dry fruits, nuts & snacks",
      "Pet food & large-volume packaging",
      "Grains, pulses & cereals",
      "Confectionery, frozen & premium food products",
    ],
  },
  {
    id: 6,
    name: "Vacuum Pouch",
    img: "/img/products/",
    hoverImg: "/img/products/",
    bg: "bg-red-500",
    popularity: 64,
    Details:
      "Vacuum pouches are specially designed packaging solutions that remove excess air, keeping products fresh for longer periods. They provide an excellent barrier against moisture, oxygen, and contaminants, making them ideal for perishable and sensitive products.",
    Features: [
      "Strong multi-layer film for maximum protection",
      "Air-tight sealing to extend product shelf life",
      "High barrier against moisture, oxygen & aroma loss",
      "Durable, puncture-resistant & food-safe material",
      "Available in clear, metallic, embossed & custom finishes",
      "Customizable sizes, thickness & printing options",
    ],
    Applications: [
      "Fresh & processed meat, poultry & seafood",
      "Cheese, dairy & frozen foods",
      "Dry fruits, nuts & snacks",
      "Spices, coffee & tea",
      "Pharmaceuticals & medical supplies",
      "Industrial & electronic components",
    ],
  },
  {
    id: 7,
    name: "Shaped Pouch",
    img: "/img/products/",
    hoverImg: "/img/products/",
    bg: "bg-red-500",
    popularity: 64,
    Details:
      "Shaped pouches are uniquely designed packaging solutions that break the monotony of traditional formats. Customized into creative shapes, they enhance shelf appeal, attract consumer attention, and help brands stand out while maintaining product freshness and protection.",
    Features: [
      "Eye-catching custom shapes for strong brand identity",
      "High-quality laminated films for durability & strength",
      "Excellent barrier against moisture, aroma & contaminants",
      "Compatible with resealable zippers, spouts, or valves",
      "Lightweight, portable & convenient for consumers",
      "Fully customizable in size, design & finishes",
    ],
    Applications: [
      "Beverages, juices & energy drinks",
      "Snacks, confectionery & candies",
      "Baby food & puree packaging",
      "Sauces, ketchups & condiments",
      "Personal care & cosmetic products",
      "Promotional & special-edition packs",
    ],
  },

  {
    id: 8,
    name: "Spout Pouch",
    img: "/img/products/Spout-Pouch.jpg",
    hoverImg: "/img/products/Spout-Pouch-Main.jpg",
    bg: "bg-green-600",
    popularity: 95,
    Details:
      "Spout pouches are innovative, flexible packaging solutions designed for liquid and semi-liquid products. With a secure spout and cap, they offer convenient pouring, reusability, and safe storage, while reducing packaging weight compared to rigid bottles or jars.",
    Features: [
      "Convenient spout & cap for easy dispensing",
      "Lightweight, flexible & travel-friendly design",
      "Strong barrier against leakage, moisture & aroma loss",
      "Durable laminated film for strength & product safety",
      "Available in various shapes, finishes & spout options",
      "Fully customizable sizes, printing & branding",
    ],
    Applications: [
      "Juices, smoothies & beverages",
      "Sauces, ketchups & condiments",
      "Liquid detergents & home care products",
      "Edible oils & energy gels",
      "Baby food & purees",
      "Personal care & cosmetic products",
    ],
  },
  {
    id: 9,
    name: "Laminated Roll-Stock",
    img: "/img/products/",
    hoverImg: "/img/products/",
    bg: "bg-red-500",
    popularity: 64,
    Details:
      "Laminated roll stock is a versatile and cost-efficient packaging material supplied in roll form. It is widely used with automated form-fill-seal (FFS) machines to create pouches and sachets. With excellent barrier properties and customization options, laminated rolls ensure product freshness, durability, and vibrant branding.",
    Features: [
      "Multi-layer laminated films for superior strength & protection",
      "Excellent barrier against moisture, oxygen & aroma loss",
      "High-speed compatibility with automatic packaging machines",
      "Lightweight, flexible & easy to transport",
      "Available in matte, glossy, metallic & transparent finishes",
      "Fully customizable thickness, width, and printing options",
    ],
    Applications: [
      "Snacks, chips & confectionery packaging",
      "Spices, pulses & powdered products",
      "Biscuits & bakery items",
      "Dairy, coffee & tea products",
      "Pharma & nutraceuticals",
      "Pet food & industrial goods",
    ],
  },
  {
    id: 10,
    name: "Poly bags ",
    img: "/img/products/Poly-bags.jpg",
    hoverImg: "/img/products/Poly-bags-Main.jpg",
    bg: "bg-green-600",
    popularity: 70,
    Details:
      "Poly bags are one of the most widely used and economical packaging solutions, made from high-quality polyethylene or polypropylene. They are lightweight, durable, and versatile, offering protection and convenience across various industries.",
    Features: [
      "Strong, flexible & lightweight packaging",
      "Excellent resistance to moisture & dust",
      "Cost-effective & suitable for bulk packaging",
      "Transparent or printed options for branding",
      "Available in multiple sizes, thicknesses & styles (LDPE, HDPE, PP)",
      "Customizable with handles, zip locks, or perforations",
    ],
    Applications: [
      "Customizable with handles, zip locks, or perforations",
      "Garments, textiles & retail packaging",
      "Industrial & hardware products",
      "Agricultural & fertilizer packaging",
      "Pharmaceuticals & medical supplies",
      "E-commerce & courier packaging",
    ],
  },
  {
    id: 11,
    name: "Security Bags",
    img: "/img/products/",
    hoverImg: "/img/products/",
    bg: "bg-red-500",
    popularity: 64,
    Details:
      "Security bags are tamper-evident packaging solutions designed to protect valuable items, confidential documents, and sensitive products during storage or transit. Built with high-strength materials and advanced sealing features, they provide safety, reliability, and peace of mind.",
    Features: [
      "Tamper-evident seal to prevent unauthorized access",
      "Tamper-evident seal to prevent unauthorized access",
      "Sequential numbering / barcoding for easy tracking",
      "Sequential numbering / barcoding for easy tracking",
      "Available in transparent or opaque options",
      "Customizable sizes, printing & security levels",
    ],
    Applications: [
      "Banking & cash handling",
      "Confidential documents & legal papers",
      "Courier & logistics services",
      "Pharmaceuticals & medical samples",
      "Evidence storage for law enforcement",
      "High-value goods & retail packaging",
    ],
  },

  {
    id: 12,
    name: "Ziplock poly bags",
    img: "/img/products/",
    hoverImg: "/img/products/",
    bg: "bg-red-500",
    popularity: 64,
    Details:
      "Ziplock poly bags are reusable and convenient packaging solutions designed with a secure interlocking closure. They offer excellent protection against dust, moisture, and contaminants while allowing easy opening and resealing, making them ideal for both consumer and industrial use.",
    Features: [
      "Resealable ziplock closure for multiple uses",
      "Lightweight, durable & transparent design",
      "Protects contents from moisture, dust & leakage",
      "Available in various sizes, thicknesses & styles",
      "Easy to open, close & reuse",
      "Customizable with printing, branding & write-on panels",
    ],
    Applications: [
      "Food items, snacks & dry fruits",
      "Pharmaceuticals & medical supplies",
      "Electronic components & accessories",
      "Jewelry, garments & retail packaging",
      "Industrial samples & hardware items",
      "Household storage & travel use",
    ],
  },
];

export default products;
